import type { CurriculumLevel } from "@prisma/client";

export type CurriculumSpec = {
  domainCode: string;
  domainName: string;
  domainDescription: string;
  level: CurriculumLevel;
  code: string;
  name: string;
  description: string;
  objectives: string[];
  targetRole: string;
  competencies: string[];
};

export const CURRICULUM: CurriculumSpec[] = [
  { domainCode: "F-ORI", domainName: "Orientation", domainDescription: "Anthropic and Claude ecosystem orientation.", level: "FOUNDATION", code: "F01", name: "Anthropic and Claude ecosystem", description: "Products, usage boundaries, and how Claude is positioned for enterprise work.", objectives: ["Distinguish Claude surfaces (claude.ai, API, Claude Code, Cowork)", "Identify appropriate vs prohibited uses", "Map ecosystem components to enterprise jobs-to-be-done"], targetRole: "Practitioner", competencies: ["CLAUDE_FUNDAMENTALS", "GOVERNANCE"] },
  { domainCode: "F-LLM", domainName: "LLM Basics", domainDescription: "LLM mechanics for practitioners.", level: "FOUNDATION", code: "F02", name: "LLM mechanics for practitioners", description: "Tokens, context windows, sampling, and failure modes that change product behavior.", objectives: ["Explain token and context constraints in operational terms", "Diagnose hallucination vs retrieval failure", "Choose temperature/tool settings for a task class"], targetRole: "Practitioner", competencies: ["CLAUDE_FUNDAMENTALS", "COST_ENGINEERING"] },
  { domainCode: "F-PRM", domainName: "Prompting", domainDescription: "Prompt engineering essentials.", level: "FOUNDATION", code: "F03", name: "Prompt engineering essentials", description: "Instruction design, constraints, examples, and evaluation of prompt quality.", objectives: ["Design prompts with role, constraints, and output contracts", "Use examples without overfitting", "Detect instruction conflict"], targetRole: "Practitioner", competencies: ["PROMPT_ENGINEERING"] },
  { domainCode: "F-CTX", domainName: "Context", domainDescription: "Context engineering.", level: "FOUNDATION", code: "F04", name: "Context engineering", description: "Selecting, ordering, and compressing the right information for a task.", objectives: ["Separate prompt engineering from context engineering", "Apply progressive disclosure", "Control signal-to-noise in long contexts"], targetRole: "Practitioner", competencies: ["CONTEXT_ENGINEERING"] },
  { domainCode: "F-RSN", domainName: "Reasoning", domainDescription: "Decomposition and verification.", level: "FOUNDATION", code: "F05", name: "Decomposition and verification", description: "Breaking work into checkable steps and verifying model output.", objectives: ["Decompose multi-step tasks", "Insert verification gates", "Distinguish reasoning theater from evidence"], targetRole: "Practitioner", competencies: ["PROMPT_ENGINEERING", "EVALUATION"] },
  { domainCode: "F-MM", domainName: "Multimodal", domainDescription: "Documents, images and PDFs.", level: "FOUNDATION", code: "F06", name: "Documents, images and PDFs", description: "Working with files, visual artifacts, and document-grounded answers.", objectives: ["Choose file vs text extraction strategies", "Ground answers in document evidence", "Handle unreadable or adversarial documents"], targetRole: "Practitioner", competencies: ["MULTIMODAL", "GROUNDING"] },
  { domainCode: "F-GRD", domainName: "Grounding", domainDescription: "Citations and evidence.", level: "FOUNDATION", code: "F07", name: "Citations and evidence", description: "Requiring provenance, quotes, and refusal when evidence is missing.", objectives: ["Design citation requirements", "Detect ungrounded claims", "Prefer evidence assembly over fluency"], targetRole: "Practitioner", competencies: ["GROUNDING"] },
  { domainCode: "F-SAF", domainName: "Safety", domainDescription: "Responsible AI and acceptable use.", level: "FOUNDATION", code: "F08", name: "Responsible AI and acceptable use", description: "Safety policies, dual-use, and escalation paths in enterprise settings.", objectives: ["Apply acceptable use to workplace scenarios", "Escalate dual-use and privacy issues", "Design human review for sensitive outputs"], targetRole: "Practitioner", competencies: ["AI_SECURITY", "GOVERNANCE"] },
  { domainCode: "F-PRD", domainName: "Productivity", domainDescription: "Claude for knowledge work.", level: "FOUNDATION", code: "F09", name: "Claude for knowledge work", description: "Research, writing, analysis, and review workflows that remain accountable.", objectives: ["Design reviewable knowledge-work loops", "Avoid silent automation of judgments", "Manage artifacts and versioning"], targetRole: "Knowledge worker", competencies: ["CLAUDE_AI", "PROMPT_ENGINEERING"] },
  { domainCode: "F-EVL", domainName: "Evaluation", domainDescription: "Introduction to evaluation.", level: "FOUNDATION", code: "F10", name: "Introduction to evaluation", description: "Task success, rubrics, and why vibe-checks fail in production.", objectives: ["Define measurable task success", "Choose rubric vs exact-match grading", "Spot vanity metrics"], targetRole: "Practitioner", competencies: ["EVALUATION"] },

  { domainCode: "P-CAI", domainName: "Claude.ai", domainDescription: "Projects and persistent context.", level: "PRACTITIONER", code: "P01", name: "Projects and persistent context", description: "Project knowledge, instructions, and contamination risks.", objectives: ["Design project memory deliberately", "Prevent stale instruction dominance", "Scope project knowledge to a job"], targetRole: "Power user", competencies: ["CLAUDE_AI", "CONTEXT_ENGINEERING"] },
  { domainCode: "P-CWK", domainName: "Cowork", domainDescription: "Claude Cowork foundations.", level: "PRACTITIONER", code: "P02", name: "Claude Cowork foundations", description: "Collaborative execution, artifacts, and human-in-the-loop cowork patterns.", objectives: ["Choose Cowork vs chat vs API", "Structure shared artifacts", "Keep humans accountable for decisions"], targetRole: "Power user", competencies: ["COWORK"] },
  { domainCode: "P-CWK", domainName: "Cowork", domainDescription: "Cowork plugins and workflow execution.", level: "PRACTITIONER", code: "P03", name: "Cowork plugins and workflow execution", description: "Plugin selection, failure handling, and workflow contracts.", objectives: ["Select plugins by trust boundary", "Handle partial workflow failure", "Avoid over-automation"], targetRole: "Power user", competencies: ["COWORK", "AGENT_ENGINEERING"] },
  { domainCode: "P-CWK", domainName: "Cowork", domainDescription: "Cowork for analytics and documents.", level: "PRACTITIONER", code: "P04", name: "Cowork for analytics and documents", description: "Spreadsheet, document, and analysis workflows with verification.", objectives: ["Verify analytical outputs", "Prevent silent numeric invention", "Design document generation with review"], targetRole: "Analyst", competencies: ["COWORK", "EVALUATION"] },
  { domainCode: "P-SKL", domainName: "Skills", domainDescription: "Agent Skill fundamentals.", level: "PRACTITIONER", code: "P05", name: "Agent Skill fundamentals", description: "Skill packaging, progressive disclosure, and metadata.", objectives: ["Design Skill structure for progressive disclosure", "Write metadata that routes correctly", "Avoid dumping large reference corpora into always-loaded context"], targetRole: "Engineer", competencies: ["SKILLS", "CONTEXT_ENGINEERING"] },
  { domainCode: "P-SKL", domainName: "Skills", domainDescription: "Build your first Skill.", level: "PRACTITIONER", code: "P06", name: "Build your first Skill", description: "Authoring, testing, and iterating a Skill for a real workflow.", objectives: ["Implement a Skill with scripts and references", "Test invocation routing", "Version a Skill safely"], targetRole: "Engineer", competencies: ["SKILLS"] },
  { domainCode: "P-SKL", domainName: "Skills", domainDescription: "Skill quality and lifecycle.", level: "PRACTITIONER", code: "P07", name: "Skill quality and lifecycle", description: "Quality bars, evaluation, deprecation, and organizational ownership.", objectives: ["Define Skill quality gates", "Detect Skill drift", "Plan ownership and retirement"], targetRole: "Engineer", competencies: ["SKILLS", "GOVERNANCE"] },
  { domainCode: "P-API", domainName: "API", domainDescription: "Claude API essentials.", level: "PRACTITIONER", code: "P08", name: "Claude API essentials", description: "Messages API, system prompts, retries, and production error handling.", objectives: ["Design robust API call patterns", "Handle overload and timeouts", "Separate system vs user vs tool content"], targetRole: "Engineer", competencies: ["CLAUDE_API"] },
  { domainCode: "P-TOL", domainName: "Tool Use", domainDescription: "Tool use and structured outputs.", level: "PRACTITIONER", code: "P09", name: "Tool use and structured outputs", description: "Tools, JSON contracts, validation, and fallbacks for downstream systems.", objectives: ["Design tool contracts", "Enforce structured output", "Recover from schema violations"], targetRole: "Engineer", competencies: ["TOOL_USE", "CLAUDE_API"] },
  { domainCode: "P-ECO", domainName: "Economics", domainDescription: "Tokens, latency and cost.", level: "PRACTITIONER", code: "P10", name: "Tokens, latency and cost", description: "Prompt caching, batching, model routing, and SLO-aware cost control.", objectives: ["Estimate token cost from a workflow", "Apply caching without stale context", "Trade latency vs quality explicitly"], targetRole: "Engineer", competencies: ["COST_ENGINEERING"] },

  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A01", name: "Claude Code setup and operating model", description: "Local setup, permissions, sandboxing, and team operating model.", objectives: ["Configure a safe operating model", "Choose permission modes by task risk", "Separate exploration from write access"], targetRole: "Staff engineer", competencies: ["CLAUDE_CODE"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A02", name: "Repository understanding", description: "Exploring unfamiliar and large repositories without context collapse.", objectives: ["Plan repository reconnaissance", "Avoid dumping entire trees into context", "Identify the right entry files"], targetRole: "Staff engineer", competencies: ["REPOSITORY_INTELLIGENCE", "CLAUDE_CODE"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A03", name: "CLAUDE.md and memory strategy", description: "Hierarchical instructions, memory, and progressive disclosure in repos.", objectives: ["Place CLAUDE.md hierarchically", "Prevent instruction scope bleed", "Design memory that stays relevant"], targetRole: "Staff engineer", competencies: ["CLAUDE_CODE", "CONTEXT_ENGINEERING"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A04", name: "Plan, execute and verify loop", description: "Planning before edits, executing in slices, and verifying with tests.", objectives: ["Force plan-before-edit on risky work", "Define verification that is not the model checking itself", "Recover from partial implementation"], targetRole: "Staff engineer", competencies: ["CLAUDE_CODE", "TESTING"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A05", name: "Git and pull-request workflows", description: "Branch isolation, diffs, PR quality, and review with Claude Code.", objectives: ["Keep Claude on isolated branches", "Produce reviewable PRs", "Prevent secret and generated-file leakage"], targetRole: "Staff engineer", competencies: ["CLAUDE_CODE"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A06", name: "Testing and quality engineering", description: "Using Claude Code to expand tests without testing the mock instead of the system.", objectives: ["Add tests that fail for the right reason", "Avoid tautological tests", "Balance unit and integration coverage"], targetRole: "Staff engineer", competencies: ["TESTING", "CLAUDE_CODE"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A07", name: "Debugging and refactoring", description: "Evidence-based debugging and refactor risk control.", objectives: ["Debug from logs and failing tests", "Refactor with characterization tests", "Avoid drive-by rewrites"], targetRole: "Staff engineer", competencies: ["DEBUGGING", "CLAUDE_CODE"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A08", name: "Hooks and event automation", description: "Lifecycle hooks, formatting, secrets scans, and dangerous automation.", objectives: ["Choose hook events correctly", "Keep hooks fast and deterministic", "Prevent recursive or privileged hook abuse"], targetRole: "Staff engineer", competencies: ["HOOKS", "CLAUDE_CODE"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A09", name: "Subagents and specialist personas", description: "When to delegate to subagents vs skills vs the main agent.", objectives: ["Avoid agent proliferation", "Delegate isolated investigation", "Keep a single owner for the diff"], targetRole: "Staff engineer", competencies: ["SUBAGENTS", "AGENT_ENGINEERING"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A10", name: "Skills and slash commands in Claude Code", description: "Project commands, skills, and reusable workflows.", objectives: ["Design commands with explicit arguments", "Keep skills scoped", "Prevent command prompt injection via untrusted files"], targetRole: "Staff engineer", competencies: ["SKILLS", "CLAUDE_CODE"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A11", name: "MCP integration from Claude Code", description: "Connecting MCP servers with least privilege from the coding agent.", objectives: ["Scope MCP tools to the task", "Handle auth and audit", "Avoid a god-server from the IDE"], targetRole: "Staff engineer", competencies: ["MCP", "CLAUDE_CODE"] },
  { domainCode: "A-CC", domainName: "Claude Code", domainDescription: "Claude Code engineering.", level: "ADVANCED", code: "A12", name: "CI/CD and non-interactive automation", description: "Headless Claude in CI, sandboxing, and unattended execution risk.", objectives: ["Design non-interactive jobs", "Constrain tools in CI", "Fail closed on ambiguous diffs"], targetRole: "Staff engineer", competencies: ["CLAUDE_CODE", "LLMOPS"] },

  { domainCode: "X-MCP", domainName: "MCP", domainDescription: "Model Context Protocol.", level: "ADVANCED", code: "X01", name: "MCP architecture", description: "Hosts, clients, servers, tools, resources, prompts, and trust boundaries.", objectives: ["Draw a correct MCP topology", "Identify trust boundaries", "Choose transport and lifecycle patterns"], targetRole: "Architect", competencies: ["MCP"] },
  { domainCode: "X-MCP", domainName: "MCP", domainDescription: "Model Context Protocol.", level: "ADVANCED", code: "X02", name: "Build an MCP server", description: "Tool contracts, schema design, errors, idempotency, and auth.", objectives: ["Design tight tool schemas", "Handle idempotency and errors", "Avoid over-broad tools"], targetRole: "Architect", competencies: ["MCP", "TOOL_USE"] },
  { domainCode: "X-AGT", domainName: "Agents", domainDescription: "Agentic systems.", level: "ADVANCED", code: "X03", name: "Agentic workflow patterns", description: "Single vs multi-agent, orchestration, checkpoints, and compensating actions.", objectives: ["Reject unnecessary multi-agent designs", "Add verification and HITL", "Design failure recovery"], targetRole: "Architect", competencies: ["AGENT_ENGINEERING"] },
  { domainCode: "X-AGT", domainName: "Agents", domainDescription: "Agentic systems.", level: "ADVANCED", code: "X04", name: "Claude Agent SDK", description: "SDK patterns for tools, sessions, and production agents.", objectives: ["Structure Agent SDK sessions", "Bound tool permissions", "Persist just enough state"], targetRole: "Architect", competencies: ["AGENT_ENGINEERING", "CLAUDE_API"] },
  { domainCode: "X-CTX", domainName: "Context", domainDescription: "Enterprise context architecture.", level: "ADVANCED", code: "X05", name: "Enterprise context architecture", description: "Knowledge fabrics, authorization-aware retrieval, and context construction.", objectives: ["Design hybrid retrieval", "Enforce authorization in context", "Avoid vector-only fabrics"], targetRole: "Architect", competencies: ["ENTERPRISE_CONTEXT", "CONTEXT_ENGINEERING"] },
  { domainCode: "X-EVL", domainName: "Evaluation", domainDescription: "Production evaluations.", level: "ADVANCED", code: "X06", name: "Production evaluations", description: "Golden sets, trajectory evals, LLM-as-judge pitfalls, and monitoring.", objectives: ["Design production eval suites", "Know when LLM-as-judge is invalid", "Track quality regressions"], targetRole: "Architect", competencies: ["EVALUATION"] },
  { domainCode: "X-SEC", domainName: "Security", domainDescription: "Security and prompt injection.", level: "ADVANCED", code: "X07", name: "Security and prompt-injection defense", description: "Direct/indirect injection, tool abuse, exfil, sandboxing, allowlists.", objectives: ["Diagnose injection classes", "Design least-privilege tool access", "Place approval gates"], targetRole: "Security architect", competencies: ["AI_SECURITY"] },
  { domainCode: "X-ARC", domainName: "Architecture", domainDescription: "Deployment patterns.", level: "ADVANCED", code: "X08", name: "Deployment patterns", description: "Serving, tenancy, VPC, fallbacks, and environment isolation.", objectives: ["Choose deployment topology", "Isolate tenants and secrets", "Plan degraded modes"], targetRole: "Architect", competencies: ["ARCHITECTURE"] },
  { domainCode: "X-OPS", domainName: "Operations", domainDescription: "Observability and LLMOps.", level: "ADVANCED", code: "X09", name: "Observability and LLMOps", description: "Tracing, token accounting, quality monitors, and incident response.", objectives: ["Instrument traces and token cost", "Alert on quality not just errors", "Debug production agent failures"], targetRole: "Architect", competencies: ["LLMOPS"] },
  { domainCode: "X-GOV", domainName: "Governance", domainDescription: "Enterprise governance.", level: "ADVANCED", code: "X10", name: "Enterprise governance and operating model", description: "Ownership, policy, model change control, and human accountability.", objectives: ["Define operating model roles", "Control model and prompt change", "Keep humans accountable"], targetRole: "Architect", competencies: ["GOVERNANCE"] },

  { domainCode: "E-ARC", domainName: "Architecture", domainDescription: "Expert architecture.", level: "EXPERT", code: "E01", name: "Claude solution architecture scenarios", description: "Principal-level design of Claude systems under constraint.", objectives: ["Produce an architecture under conflicting constraints", "Make explicit tradeoffs", "Defend a topology to executives and engineers"], targetRole: "Principal", competencies: ["ARCHITECTURE", "LEADERSHIP"] },
  { domainCode: "E-DOM", domainName: "Domain", domainDescription: "Healthcare and life sciences.", level: "EXPERT", code: "E02", name: "Healthcare and life-sciences patterns", description: "Privacy, provenance, HITL, and domain workflows — not medical advice.", objectives: ["Design privacy-preserving Claude systems", "Require evidence and audit trails", "Keep clinicians/staff in the loop"], targetRole: "Principal", competencies: ["HEALTHCARE_LS", "GOVERNANCE", "AI_SECURITY"] },
  { domainCode: "E-MOD", domainName: "Modernization", domainDescription: "Claude-powered modernization.", level: "EXPERT", code: "E03", name: "Claude-powered modernization", description: "Using Claude to modernize estates without unsupervised rewrites.", objectives: ["Sequence modernization with verification", "Contain blast radius", "Measure value not lines generated"], targetRole: "Principal", competencies: ["MODERNIZATION", "ARCHITECTURE"] },
  { domainCode: "E-LED", domainName: "Leadership", domainDescription: "Value realization.", level: "EXPERT", code: "E04", name: "Value realization and adoption", description: "Operating model, change, ROI, and capability building.", objectives: ["Define value hypotheses", "Design adoption without shadow IT", "Build internal Claude capability"], targetRole: "Principal", competencies: ["LEADERSHIP"] },
  { domainCode: "E-CAP", domainName: "Capstone", domainDescription: "Domain capstone delivery.", level: "EXPERT", code: "E05", name: "Domain capstone delivery", description: "End-to-end governed Claude solution design under a multi-dimensional rubric.", objectives: ["Deliver architecture, context, MCP, security, eval, observability, HITL, cost, and governance as one design"], targetRole: "Principal", competencies: ["ARCHITECTURE", "MCP", "AI_SECURITY", "EVALUATION", "LLMOPS", "GOVERNANCE", "HEALTHCARE_LS"] },
];

export const COMPETENCIES: { code: string; name: string; description: string; cluster: string }[] = [
  { code: "CLAUDE_FUNDAMENTALS", name: "Claude Fundamentals", description: "Ecosystem, mechanics, and appropriate use.", cluster: "foundation" },
  { code: "PROMPT_ENGINEERING", name: "Prompt Engineering", description: "Instruction design and constraint specification.", cluster: "foundation" },
  { code: "CONTEXT_ENGINEERING", name: "Context Engineering", description: "Selection, ordering, compression, and progressive disclosure.", cluster: "context" },
  { code: "GROUNDING", name: "Grounding", description: "Evidence, citations, and refusal when unsupported.", cluster: "foundation" },
  { code: "MULTIMODAL", name: "Multimodal", description: "Documents, images, and PDFs.", cluster: "foundation" },
  { code: "CLAUDE_AI", name: "Claude.ai", description: "Projects, persistent context, and product workflows.", cluster: "practitioner" },
  { code: "COWORK", name: "Cowork", description: "Collaborative execution and plugins.", cluster: "practitioner" },
  { code: "SKILLS", name: "Skills", description: "Agent Skills packaging and lifecycle.", cluster: "practitioner" },
  { code: "CLAUDE_API", name: "Claude API", description: "Messages API and production integration.", cluster: "practitioner" },
  { code: "TOOL_USE", name: "Tool Use", description: "Tools, structured outputs, and contracts.", cluster: "practitioner" },
  { code: "COST_ENGINEERING", name: "Cost Engineering", description: "Tokens, latency, caching, and routing.", cluster: "practitioner" },
  { code: "CLAUDE_CODE", name: "Claude Code", description: "Agentic coding operating model.", cluster: "claude-code" },
  { code: "REPOSITORY_INTELLIGENCE", name: "Repository Intelligence", description: "Understanding large and unfamiliar codebases.", cluster: "claude-code" },
  { code: "TESTING", name: "Testing", description: "Quality engineering with Claude.", cluster: "claude-code" },
  { code: "DEBUGGING", name: "Debugging", description: "Evidence-based diagnosis and repair.", cluster: "claude-code" },
  { code: "HOOKS", name: "Hooks", description: "Lifecycle automation in Claude Code.", cluster: "claude-code" },
  { code: "SUBAGENTS", name: "Subagents", description: "Specialist delegation without proliferation.", cluster: "claude-code" },
  { code: "MCP", name: "MCP", description: "Model Context Protocol architecture and servers.", cluster: "enterprise" },
  { code: "AGENT_ENGINEERING", name: "Agent Engineering", description: "Agentic workflow design and orchestration.", cluster: "enterprise" },
  { code: "ENTERPRISE_CONTEXT", name: "Enterprise Context", description: "Knowledge fabrics and authorized context construction.", cluster: "enterprise" },
  { code: "EVALUATION", name: "Evaluation", description: "Offline and production evaluation of Claude systems.", cluster: "enterprise" },
  { code: "AI_SECURITY", name: "AI Security", description: "Injection, exfil, sandboxing, and least privilege.", cluster: "enterprise" },
  { code: "ARCHITECTURE", name: "Architecture", description: "Solution and deployment architecture.", cluster: "expert" },
  { code: "LLMOPS", name: "LLMOps", description: "Observability, operations, and change control.", cluster: "enterprise" },
  { code: "GOVERNANCE", name: "Governance", description: "Policy, ownership, and accountability.", cluster: "expert" },
  { code: "HEALTHCARE_LS", name: "Healthcare/LS", description: "Healthcare and life-sciences Claude patterns.", cluster: "expert" },
  { code: "MODERNIZATION", name: "Modernization", description: "Claude-powered estate modernization.", cluster: "expert" },
  { code: "LEADERSHIP", name: "Leadership", description: "Value realization and adoption leadership.", cluster: "expert" },
];
